---
spellbook_dns_master: true
spellbook_dns_slave: false
spellbook_forwarder_list:
  - 223.5.5.5
spellbook_zones_list: 
  - dns.v.com

spellbook_slaves_list:
  - 192.168.2.11
  - 192.168.2.12
spellbook_internal_list:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
spellbook_dns_masters_list: 
  - "192.168.2.11"
spellbook_dns_v_records:
  - "ns1             IN  A     192.168.2.11"
  - "ns2             IN  A     192.168.2.12"
  - "www             IN  A     192.168.2.11"
  - "master          IN  CNAME www"
  - "slave           IN  A     192.168.2.12"