spellbook_resolv_config: true 
spellbook_network_config: true
spellbook_swap_off: true
spellbook_firewalld_off: true
spellbook_instant_sync_time: true
spellbook_install_nfs: true
spellbook_network_config_dns: false
spellbook_network_manager_dns: false

spellbook_domain_name_server_ip:
  - 192.168.2.11
  - 192.168.2.12
spellbook_domain_name_options_timeout: "2"
spellbook_domain_name_options_attempts: "2"
spellbook_domain_name_options_search:
  - "dns.v.com"