- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"
 
- name: Stop and disable ufw
  command: "ufw disable"
  when: ansible_os_family == "Debian"