---
- name: Gather facts
  setup:

- import_tasks: swap.yml
  when: swap_off

- import_tasks: firewalld.yml
  when: firewalld_off

- import_tasks: chronyc.yml
  when: instant_sync_time

- import_tasks: nfs-client.yml
  when: install_nfs 

- import_tasks: network.yml
  vars:
    - network_config_dns: true
  when: ansible_default_ipv4 is defined
        and network_config == true

- import_tasks: resolv.yml
  when: resolv_config