---
- name: Gather facts
  setup:

- import_tasks: swap.yml
  when: spellbook_swap_off

- import_tasks: firewalld.yml
  when: spellbook_firewalld_off

- import_tasks: chronyc.yml
  when: spellbook_instant_sync_time

- import_tasks: nfs_client.yml
  when: spellbook_install_nfs 

- import_tasks: network.yml
  vars:
    - spellbook_network_config_dns: true
  when: ansible_default_ipv4 is defined
        and spellbook_network_config == true

- import_tasks: resolv.yml
  when: spellbook_resolv_config