---
- name: Install nfs client package 
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Install nfs client package 
  yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"


- name: Install rpcbind package 
  yum:
    name: rpcbind
    state: present
  when: ansible_os_family == "RedHat"