- name: Configure resolv.conf delete domain name server ip 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: absent
    regexp: '^nameserver'

- name: Configure resolv.conf domain name server ip 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: present
    insertafter: '^nameserver'
    line: "nameserver {{ item }}"
  loop:  "{{ spellbook_domain_name_server_ip }}"

- name: Configure resolv.conf delete options 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: absent
    regexp: '^options'

- name: Configure resolv.conf options 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: present
    regexp: '^options'
    line: "options timeout:{{ spellbook_domain_name_options_timeout }} attempts:{{ spellbook_domain_name_options_attempts }}"
  
- name: Configure resolv.conf delete search 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: absent
    regexp: '^search'

- name: Configure resolv.conf search 
  lineinfile:
    path: "{{ spellbook_resolv_path }}"
    state: present
    regexp: '^search'
    line: "search {{ spellbook_domain_name_options_search | join(' ') }}" 