- import_tasks: install.yml
  when: 
    spellbook_dns_master == true
    or spellbook_dns_slave == true

- import_tasks: config.yml
  when: 
    spellbook_dns_master == true
    or spellbook_dns_slave == true 

- import_tasks: add_zone.yml
  when: 
    spellbook_dns_master == true
    or spellbook_dns_slave == true