---
- name: Install docker
  dnf:
    name:
    - docker
    state: present
    update_cache: yes

- name: Start offline file repot container 
  command: docker run --rm -itd -p 80:80 registry.cn-beijing.aliyuncs.com/spellbook/offline-file:nginx-v1.0.0