---
- name: Flush all iptables rules
  command: "{{ spellbook_iptables_bin_dir }}/iptables -F"
  ignore_errors: yes
  when: spellbook_clean_kubenets_node == true or spellbook_clean_kubenets_master==true

- name: Delete all non-default chains in iptables
  command: "{{ spellbook_iptables_bin_dir }}/iptables -X"
  when: spellbook_clean_kubenets_node == true or spellbook_clean_kubenets_master==true