---
- name: Remove k8s related files and subdirectories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /root/.kube
    - /var/lib/etcd
    - /etc/cni/net.d
  when: spellbook_clean_kubenets_master == true or spellbook_clean_kubenets_node == true
