---
- name: Add zone databases
  template:
    src: "{{ item }}.zone.j2"
    dest: "/var/named/{{ item }}.zone"
    mode: 0640
    owner: root
    group: named 
  with_items: "{{ zones_list }}"
  notify: 
    - Reload named daemon