- import_tasks: install.yml
  when: 
    dns_master == true
    or dns_slave == true

- import_tasks: config.yml
  when: 
    dns_master == true
    or dns_slave == true 

- import_tasks: add_zone.yml
  when: 
    dns_master == true
    or dns_slave == true