---
spellbook_check_network_server: true
spellbook_network_config_dns: false 
spellbook_network_manager_dns: false

spellbook_domain_name_server_ip: 
  - "223.5.5.5"
spellbook_domain_name_options_timeout: "2"
spellbook_domain_name_options_attempts: "2"
spellbook_domain_name_options_search:
  - "dns.v.com"