---
- import_tasks: check_network_server.yml
  when: spellbook_check_network_server == true 

- import_tasks: dns.yml
  when: spellbook_network_config_dns == true 
        and spellbook_check_network_server == true 