---
- name: Create a destination directory
  file:
    path: "{{ spellbook_velero_work_dir }}"
    state: directory

- name: Download and extract a tar file
  unarchive:
    remote_src: yes
    src: "{{ spellbook_velero_download_url }}"
    dest: "{{ spellbook_velero_work_dir }}"
    owner: root
    group: root
    mode: 0644

- name: Install velero binary to dest machine
  copy:
    remote_src: yes
    src: "{{ spellbook_velero_work_dir }}/{{ spellbook_velero_release_version }}/velero"
    dest: "{{ spellbook_velero_bin_dir }}/velero"
    mode: 0770
    owner: root
    group: root

- name: copy veleroo script
  template:
    src: "veleroo.j2"
    dest: "{{ spellbook_velero_bin_dir }}/veleroo"
    mode: 0770
    owner: root
    group: root 

- name: copy velero auth file 
  template:
    src: "velero_auth.txt.j2"
    dest: "{{ spellbook_velero_auth_file }}"
    mode: 0640
    owner: root
    group: root 

- name: Install velero
  shell: "{{ spellbook_velero_bin_dir }}/velero --kubeconfig ~/.kube/config install --provider aws --image {{ spellbook_registry }}/{{ spellbook_velero_image }}:{{ spellbook_velero_version }}  --plugins {{ spellbook_registry }}/{{ spellbook_velero_plugin_for_aws_image }}:{{ spellbook_velero_plugin_for_aws_version }}  --bucket {{ spellbook_velero_s3_bucket }} --secret-file {{ spellbook_velero_auth_file }}  --use-volume-snapshots=false --namespace {{ spellbook_velero_namespace }} --backup-location-config region={{ spellbook_velero_s3_region }},s3ForcePathStyle='{{ spellbook_velero_s3_force_path_style }}',s3Url={{ spellbook_velero_s3_url }}"