---

- import_tasks: resolv.yml
  when: resolv_config

- import_tasks: swap.yml
  when: swap_off

- import_tasks: firewalld.yml
  when: firewalld_off

- import_tasks: chronyc.yml
  when: instant_sync_time

- import_tasks: nfs-client.yml
  when: install_nfs 