---

- name: Remove fstab swap partition
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
  - swap
  - none

- name: Check using swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no
  check_mode: no

- name: Disable swap
  command: /sbin/swapoff -a
  when: swapon.stdout
