---
- hosts: dnsmaster
  gather_facts: False
  roles:
    - spellbook.named
  vars:
    - spellbook_dns_master: true
    - spellbook_dns_slave: false
  tags:
    - spellbook_dns_master

- hosts: dnsslave
  gather_facts: False
  roles:
    - spellbook.named
  vars:
    - spellbook_dns_master: false
    - spellbook_dns_slave: true
  tags:
    - spellbook_dns_slave