---

- hosts:
    - all
  become: yes
  become_user: root
  roles:
    - spellbook.standardize

- hosts:
    - kube
  become: yes
  become_user: root
  roles:
    - spellbook.tuning
  vars:
  - spellbook_tuning_ip_forward: 1
  - spellbook_tuning_tcp_tw_reuse: 1