---

- hosts:
    - all
  become: yes
  become_user: root
  roles:
    - spellbook.repo
  vars:
    - spellbook_repo_enable: true

- hosts:
    - all
  become: yes
  become_user: root
  roles:
    - spellbook.ntp

- hosts:
    - all
  become: yes
  become_user: root
  roles:
    - spellbook.kernel

- hosts:
    - all
  become: yes
  become_user: root
  roles:
    - spellbook.standardize

- hosts:
    - all 
  become: yes
  become_user: root
  roles:
    - spellbook.tuning

- hosts:
    - kube
  become: yes
  become_user: root
  roles:
    - spellbook.tuning
  vars:
  - spellbook_tuning_ip_forward: 1
  - spellbook_tuning_tcp_tw_reuse: 1

- hosts:
  - all
  become: yes
  become_user: root
  roles:
  - spellbook.utility